language: go
branches:
  only:
    - master
    - test_travis
before_script:
  - env GO111MODULE=on go mod download
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - env GO111MODULE=on go test -coverprofile c.out ./...
after_script:
  - ./cc-test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT